

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  spark:
    image: bitnami/spark:latest
    environment:
      SPARK_MODE: master
    ports:
      - "8080:8080"

  kafka_producer:
    build: ./kafka_producer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
    restart: always

  kafka_consumer:
    build: ./kafka_consumer
    depends_on:
      - kafka
      - mongodb
    environment:
      KAFKA_BROKER: kafka:9092
      MONGO_URI: mongodb://admin:password@mongodb:27017
    restart: always

  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  dashboard:
    build: ./dashboard
    ports:
      - "8050:8050"
    depends_on:
      - api
